language: node_js

node_js:
  - '6'
  - '8'

cache:
  directories:
    - ~/.npm

script:
  - npm run lint
  - npm run build
  - npm run cover

after_success:
  # Upload coverage to codecov
  - nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json

before_deploy:
  - npm run typedoc
deploy:
  provider: surge
  project: ./typedoc/
  domain: iterare.surge.sh
  skip_cleanup: true
